version: "3.1"
services:
    web:
        build: .
        ports:
            - "3000:3000"
        env_file:
            - .env
        environment:
            DATABASE_URL: "mongodb://mongodb_uv:27017/undverkauft_db"
        volumes:
            - type: bind
              source: ./public
              target: /app/public

    mongo:
        hostname: postgres
        container_name: mongodb_uv
        image: mongo
        restart: always
        env_file:
            - .env_mongodb
        ports:
            - 27017:27017
        volumes:
            - type: volume
              source: mongo-data
              target: /data/db

volumes:
    mongo-data:
